### ISSUE TITLE
Support npm install <tarball>

### ISSUE THREAD

**Issue by ttghr** [JamieMason/shrinkpack#10]
When you use socket.io you run into following issue:

``` javascript
"xmlhttprequest": {
    "version": "1.5.0",
    "from": "https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz",
    "resolved": "https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz"
},,
```

will be resolved to npm cache add xmlhttprequest@1.5.0 and that is not the same package as "from"  describes.
With the effect, that socket.io crashes after installing with the packages from node_shrinkwrap.

Solution:
change line 110 in index.js to:

``` javascript
          .exec('../npm cache add "' + value.from + '"')
```

**Comment by JamieMason** [comment]
Thanks ever so much. I'm on holiday but will pick up when I return home.

**Comment by JamieMason** [comment]
Am I right that the package.json entry in `dependencies` looks like this?

``` javascript
"xmlhttprequest": "https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz"
```

**Comment by ttghr** [comment]
Yes, you are right !
