### ISSUE TITLE
API and responsibilities

### ISSUE THREAD

**Issue by Raynos** [JamieMason/shrinkpack#11]
I looked at this tool and the README and became pretty excited!

I ran `shrinkpack -h` and it immediately did `rm -rf node_modules; rm npm-shrinkwrap.json; npm install`. I was surprised and a bit sad as I forgot to `git add .`

I would like to propose that this program does not run `.clean()`. Deleting all of these files is going to generate a lot of churn and also take a lot of time.

Furthermore running `.rebuild()` is also not a good idea. The application developer should drive npm install and shrinkwrap itself. I have an `npm-shrinkwrap` module ( https://github.com/uber/npm-shrinkwrap ) that I use as a better shrinkwrap and I want to use this module as well.

I would like to propose that this program only does the `.save()` path.

I'd be willing to open a pull request (with tests!!) to implement this if the feature is welcome. 

I would also implement a `-h` and `--help` output.

**Comment by JamieMason** [comment]
I completely agree @Raynos, **shrinkwrap** (managing `npm-shrinkwrap.json`) and **shrinkpack** (managing `node_shrinkwrap/*.tgz`) should be separate concerns. 

I see shrinkpack in it's current state as a working prototype, it needs a lot of attention to make it acceptable for general use. 

With this in mind, what are your thoughts on the following interface? 

`shrinkpack --help`
+ Display typical help output.

`shrinkpack clean` 
+ `rm -rf node_shrinkwrap`
+ `rm npm-shrinkwrap.json`

Removing npm-shrinkwrap.json might be crossing concerns, but it needs to be either removed or updated to point at the npm registry anyway if the tarballs are going to be missing. We should either remove the dependency graph or regenerate it — what do you think?

`shrinkpack save`
+ Update the contents of `node_shrinkwrap/` so they match `npm-shrinkwrap.json`.
+ Update `npm-shrinkwrap.json` to point at those tarballs.
+ Remove redundant tarballs, add new ones etc.

`shrinkpack index`

I'm really tempted to have another command in there to regenerate `npm-shrinkwrap.json` (which likely delegates to [npm-shrinkwrap](https://github.com/uber/npm-shrinkwrap)). This is for convenience but more to remove the need to explain in the README that to use this tool you need to first download and install `other-tool` and run `other-tool command` before you're able to run shrinkpack — the need to include all this explanation makes the tool seem more complicated in my opinion.

A Developer can still use another method of updating their `npm-shrinkwrap.json` if they want to and just use shrinkpack for `node_shrinkwrap/*.tgz`, but the standard workflow is simpler for having this delegate included.

Everything is open to change and ideas, what do you think? I'm not happy with command names I've suggested, I'm sure they can be improved.

Thanks a lot.

**Comment by JamieMason** [comment]
Please give me your thoughts on 0.3.0 @Raynos. Shrinkpack now only manages the contents of node_shrinkwrap based on the contents of the npm-shrinkwrap.json - and no longer creates it for you.

It should now also be much faster, as it only removes redundant packages and adds new ones - with the others being left as they were.

Ideas or changes welcome, thanks.
