### ISSUE TITLE
Handle scoped packages

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/shrinkpack#12]
Examples such as the following from engine.io-client@1.5.4.

``` json
"xmlhttprequest": {
  "version": "1.5.0",
  "from": "xmlhttprequest@https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz",
  "resolved": "./node_shrinkwrap/a6b6f2.tar.gz"
}
```

`npm cache add` does not seem to cache this format.

**Comment by DylanPiercey** [comment]
@JamieMason Is this referring to https://docs.npmjs.com/misc/scope? If so this would be awesome to have.

**Comment by digitalsadhu** [comment]
@JamieMason  I've just run into this. Any thoughts on how to approach fixing it? I could try and work on a PR if you could point me in the right direction...

**Comment by JamieMason** [comment]
Thanks @digitalsadhu. 

It's a while since I opened this issue, but I just tried the following which proves it is cached correctly.

```
$ npm cache clean
$ npm cache add xmlhttprequest@https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
$ npm cache ls
~/.npm
~/.npm/xmlhttprequest/
~/.npm/xmlhttprequest/1.5.0/
~/.npm/xmlhttprequest/1.5.0/package.tgz
~/.npm/xmlhttprequest/1.5.0/package/
~/.npm/xmlhttprequest/1.5.0/package/package.json
```

But that's using npm via the command line and shrinkpack uses npm via `require('npm')` and I think it's the latter where this bit of support is lacking.

When I first wrote shrinkpack, npm had documentation for an API available via `require('npm')`, but that has [since been removed](https://twitter.com/fold_left/status/671635475036246016).

I need to update shrinkpack, but this _may_ also be enough to fix this issue — by changing the implementation of [./src/npmCache.js](https://github.com/JamieMason/shrinkpack/blob/ce673a443841cab716e2557d226516a060cdd78b/src/npmCache.js) to instead call `npm cache add x` using [child_process.exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback).

If you were to open a PR, that would be great.

Thanks all.

Jamie

**Comment by JamieMason** [comment]
working locally using

``` json
"dependencies": {
    "@digitaledgeit/paypal": "0.3.1"
}
```

**Comment by JamieMason** [comment]
Version [0.5.0](https://github.com/JamieMason/shrinkpack/blob/master/CHANGELOG.md) has been released, please could you give it a try and update or close this issue? 

Thanks a lot @digitalsadhu @DylanPiercey

**Comment by DylanPiercey** [comment]
@JamieMason seems to work well now but I am having one minor issue. Scoped packages always seem to be "repacked" every time I run shrinkpack.

![image](https://cloud.githubusercontent.com/assets/4985201/14234192/e2653602-f999-11e5-8ca6-5352847375e5.png)

This could be a limitation with npm or something but I thought i'd bring it up.

---

Edit:

Although shrinkpack now successfully runs it doesn't actually put scoped modules into the `node_shrinkwrap` folder. Typically when you install scoped modules they are all placed in one folder (such as `./@digitaledgeit/` in your example) however I don't see a folder for my `@rill` modules in the `node_shrinkwrap` folder.
