### ISSUE TITLE
Shrinkpack fails with repos not in npm registry

### ISSUE THREAD

**Issue by dmkelly** [JamieMason/shrinkpack#22]
I'm using a repo that isn't listed in the npm registry, so `npm view` fails [here](https://github.com/JamieMason/shrinkpack/blob/master/src/npmCache.js#L37).

Do you have any plans to support this use case?

**Comment by JamieMason** [comment]
Thanks @dmkelly, please could you post your package.json so I can reproduce the issue?

**Comment by dmkelly** [comment]
The failing package is hosted on Github Enterprise on a private network so unfortunately I can't provide a package.json that you will be able to use to reproduce. I thought I saw in your commit history that you added a fix to support packages referenced by Github URL in the package.json, so maybe this issue is more related to the package being hosted on a private network?

**Comment by DylanPiercey** [comment]
@dmkelly I am using bitbucket for some private repo's (accessed with ssh keys) and recent changes allow that to work, perhaps give it another go?

---

Edit:

It worked with 0.5x but no longer works with 0.6x

``` console
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/a-private-package
```

@JamieMason I'm not sure what changes were made in 0.6 but is this something that could be resolved?

**Comment by dmkelly** [comment]
I just tested and can confirm that it works on 0.5.0 but does not work on 0.6.0

Thanks, @DylanPiercey

**Comment by JamieMason** [comment]
Hi all, please could you retry this using [0.10.0](https://github.com/JamieMason/shrinkpack/releases/tag/0.10.0) and re-open if you find issues? thanks.
