### ISSUE TITLE
Repeated "No compatible version found" error calling npm i after shrinkpack

### ISSUE THREAD

**Issue by adam-marshall** [JamieMason/shrinkpack#24]
Seems to be a different module that fails each time, no specific version

E.g. 
234 error notarget No compatible version found: assemble-less@'./node_shrinkwrap/assemble-less-0.7.0.tgz'
419 error notarget No compatible version found: grunt@'./node_shrinkwrap/grunt-0.4.5.tgz'
420 error notarget No compatible version found: grunt-contrib-concat@'./node_shrinkwrap/grunt-contrib-concat-1.0.0.tgz'

If I call npm i a few different times I get a different message. There doesn't seem to be anything wrong with the versions, the tarball version matches the ones in the error message. 

Not sure if it is due to the size of the package.json/number of dependencies, or if I am simply doing this wrong :)

**Comment by JamieMason** [comment]
which OS are you on? could you include the package.json here please? thanks

**Comment by adam-marshall** [comment]
Windows 7.

[package.json.txt](https://github.com/JamieMason/shrinkpack/files/205954/package.json.txt)

Thanks! Your solution seems perfect for what we need so thank you for your help.

**Comment by webuniverseio** [comment]
Hi, I tested on Windows 10 with shrinkwrap 0.6.0 and process was successful for me (both shrinkpack and npm i after shrinkpack).
My node -v is v4.1.0 and npm -v is 3.8.3.

Steps I followed:
- copied your package.json in empty folder, then run `npm i`
- `npm shrinkwrap --dev` after installation
- `shrinkpack`
- removed node_modules and run `npm i` again

**Comment by JamieMason** [comment]
thanks so much for that @szarouski, really helps. @adam-marshall please could you re-test?

**Comment by JamieMason** [comment]
Please re-open if this is still an issue, thanks.
