### ISSUE TITLE
Error handling issues obscuring points of error (in v0.6.0)

### ISSUE THREAD

**Issue by thedewi** [JamieMason/shrinkpack#25]
in src/exec.js:

```
      } else if (stderr) {
        reject(err);
```

Problems are a bit tricky to trace due to some error handling issues:
1. The reject() is passing out `err` instead of `stderr`, which is `null` so it blows up the `.toString()` in npmCache.js:42.

Recommendation: substitute those, use String() rather than .toString().
1. And when `addToNpmCache()` catches and returns errors, `addMissingDep()` is proceeding to `addToShrinkpack` with the error as its `dep` argument. Because that argument is missing all the usual properties, it usually ends with: `TypeError: Cannot read property 'npm' of undefined`

Recommendation: move the `addToNpmCache()` catch to the end of `addToNpmCache()`'s promise chain, so that it doesn't try to proceed with `addToShrinkpack()`, but can continue to process other deps.

**Comment by JamieMason** [comment]
brilliant @thedewi, thanks.

**Comment by JamieMason** [comment]
Thanks a lot for your help, this should be improved in [0.10.0](https://github.com/JamieMason/shrinkpack/releases/tag/0.10.0).
