### ISSUE TITLE
linter (standard/semistandard)

### ISSUE THREAD

**Issue by fanatid** [JamieMason/shrinkpack#27]
As I see you use parts from `semistandard`/`standard` with `eslint`, why not just use `semistandard`/`standard`? Thank you!

**Comment by JamieMason** [comment]
Thanks @fanatid, it's the first time I've used semistandard – if you can show me the right way in the form of a PR, that would be great if you have time.

**Comment by JamieMason** [comment]
This is released, thanks a lot – much better after your changes.
