### ISSUE TITLE
drop node 0.10 / 0.12

### ISSUE THREAD

**Issue by fanatid** [JamieMason/shrinkpack#29]
Why not drop support for node 0.10? and even 0.12?
Promises are available from 0.12, arrow functions (awesome feature!) available from node 4.

**Comment by JamieMason** [comment]
Thanks a lot for this and the other issues and PRs, I'll get onto them this weekend. Huge help, cheers.

**Comment by mlarcher** [comment]
Is O.10 actually still supported ? We are stuck with it and when trying to use shrinkpack we get an error `TypeError: Object #<Object> has no method 'execSync'`. It seems that childProcess.execSync was introduced in 0.11 but is used in isNpm3Up.js. Thoughts ?
N.B. if older version of node are not supported anymore, I'd be happy to know which older version of shrinkpack we can safely use with node 0.10

**Comment by fanatid** [comment]
@mlarcher 0.10 will be supported until 2016-10-01. You can familiarize with schedule here: https://github.com/nodejs/LTS
`execSync` was added in 0.12

**Comment by mlarcher** [comment]
@fanatid : I meant supported by shrinkpack, obviously. Thanks for pointing out the correct node version implementing the concerned function,  though :)

**Comment by JamieMason** [comment]
Thanks guys, I'll get this fixed. I need to set up nvm or similar on my home machine, I currently just have a global install of node v4.

**Comment by mlarcher** [comment]
Great news @jamieMason ! Please let me know if I can be of any assistance.

**Comment by pgAdmin** [comment]
MeteorJS refers to use of Shrinkpack. However, it internally bundles Node v0.10.46 which is not supported by Shrinkpack yet.

This PR solves the issue. https://github.com/JamieMason/shrinkpack/pull/60

**Comment by JamieMason** [comment]
I've marked shrinkpack as officially supporting node v4 as a minimum as 0.x support is being phased out in node itself. I can't be sure whether shrinkpack's dependencies will continue to support 0.x but if there are any ways I can add support in shrinkpack itself I will try to address them.

Leaving this open for further investigation.

**Comment by SPSpwetter** [comment]
FYI, os.homedir() is in node4 minimum. See https://github.com/nodejs/node/issues/3148 so I concur with the dropping support for node < 4.

**Comment by ocombe** [comment]
In the latest release (0.17.1) I got the following warning as well: `(node:13896) DeprecationWarning: execa.spawn() is deprecated. Use execa() instead.`
I guess you can update this too :)

**Comment by JamieMason** [comment]
Going to close this please folks, I think it is addressed? We have `"node": ">=4.0"` under `"engines"` in package.json and are using arrow functions etc in the codebase. The next version of `shrinkpack` will be TypeScript with es3 as the transpilation target. Please comment if I've overlooked anything you raised here, thanks.
