### ISSUE TITLE
Local package resolution is very slow

### ISSUE THREAD

**Issue by markerikson** [JamieMason/shrinkpack#32]
#### Expected behaviour

Running "shrinkpack" and having unresolved packages should be able to resolve almost all the packages very quickly, since Shrinkpack just needs to open up the correct package.json for each unresolved dependency.
#### Actual behaviour

Running Shrinkpack on an npm-shrinkwrap.json with roughly 250 unresolved dependencies takes at _least_ 10-15 minutes to execute, with Node pegging a CPU core the entire time.
#### Steps to reproduce

See "actual behavior"
#### Software versions used

OS         :  Windows 7
node.js    :  5.1
npm        :  3.7.2
shrinkpack : 0.10.0
#### Log output when running shrinkpack

```
i 825 dependencies in npm-shrinkwrap.json
i 248 have a missing "resolved" property
i 0 need removing from ./node_shrinkwrap
i 247 need adding to ./node_shrinkwrap
i 247 are in your npm cache
i 0 need downloading
√ set missing "resolved" property for alter@0.2.0 to http://registry.npmjs.org/alter/-/alter-0.2.0.tgz
√ set missing "resolved" property for amdefine@1.0.0 to http://registry.npmjs.org/amdefine/-/amdefine-1.0.0.tgz
√ set missing "resolved" property for ansi-regex@2.0.0 to http://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz
[ snipped]
```
#### Notes

I noted that the slowdown seems to be due to the use of `glob.sync()`, per this snippet:

``` js
function getPkgPath (dep) {
  return glob.sync('node_modules/**/' + dep.name + '/package.json', {
    realpath: true
  })[0] || '';
}
```

I was able to implement at least a partial fix by replacing the use of `glob.sync()` with `fs.accessSync`, (per http://stackoverflow.com/questions/4482686/check-synchronously-if-file-directory-exists-in-node-js ), and just constructing the path to package.json directly:

``` js
function getPkgPath (dep) {
  var depPackagePath = "node_modules/" + dep.name + "/package.json";
  var result = '';
  try {
    fs.accessSync(depPackagePath, fs.F_OK);
    result = fs.realpathSync(depPackagePath);
  } 
  catch (e) {
    // It isn't accessible
  }

  return result;
}
```

This approach resulted in _vastly_ faster resolution times, and the entire operation, including resolving all 250 entries, finished in somewhere under 30 seconds.

I was about to submit this as a PR when I realized that while this works great under NPM3, it probably won't work all the time under NPM2, which I'm guessing is why you were doing the glob check first.

Perhaps the two approaches could be combined - assume the package exists at the top-level of `node_modules` and do the fast direct lookup first, and only do a glob check if that fails.

In fact, now that I think about it, that seems like a good compromise.  I'll go ahead and submit a PR to that effect now.

**Comment by JamieMason** [comment]
A change based on your PR has been released in 0.10.2, please let me know your thoughts @markerikson. Thanks again for your great help, grateful for your time.

**Comment by markerikson** [comment]
Hmm.  Just tried out 0.10.2, and a couple things don't seem right:

First, Shrinkpack is now declaring that almost every item in my npm-shrinkwrap.json file is missing a "resolved" property:

```
i 837 dependencies in npm-shrinkwrap.json
i 824 have a missing "resolved" property
i 0 need removing from ./node_shrinkwrap
i 259 need adding to ./node_shrinkwrap
i 259 are in your npm cache
i 0 need downloading
```

This seems to be due to bb8f7df8b2543998ef2214ac1a87ba854cf15e50 , and I'm not sure I follow the reasoning behind it.

Second, it looked like Shrinkpack successfully updated all missing "resolved" properties in a couple seconds, but then began trying to run `npm view` on pretty much everything all over again.

I'll have to do some investigation on this later.

**Comment by JamieMason** [comment]
> This seems to be due to bb8f7df , and I'm not sure I follow the reasoning behind it.

Yeah, this was a bad idea at gone 11pm. I've reverted it in develop, which I'll push shortly.

> Second, it looked like Shrinkpack successfully updated all missing "resolved" properties in a couple seconds, but then began trying to run npm view on pretty much everything all over again.

Thanks, I'll check this out next.

**Comment by markerikson** [comment]
> Yeah, this was a bad idea at gone 11pm. I've reverted it in develop, which I'll push shortly.

Aww, c'mon!  Everyone knows that you're supposed to program _better_ late at night, not worse! :)

At the moment I'm not sure if the behavior I'm seeing is entirely a "real" bug with Shrinkpack, or whether it's due to the project config I've been testing it on.  I'll poke around this evening to try to get a better idea what's happening.

**Comment by JamieMason** [comment]
hehe, I'm an early bird :)

I'm looking to improve the logging in that area at the moment as it's fairly complicated now. Broadly speaking the way it works at the moment is;
1. optimistically look for a package.json in npm 3's flat structure.
2. if that fails, run glob for package.json files once and cache the results in memory.
3. query that object for each dependency that needs resolving.
4. look for the dist.tarball value in the matched package.json.
5. if that fails, query the remote registry.
6. look for the dist.tarball value in the response json.

**Comment by lime** [comment]
It's exciting to follow along with the rapid development here, thanks for the work you're doing!

I tried out the newest changes on a large npm 2 repo, and my node process ran out of memory. 😅 Some quick benchmarking showed that async `glob` uses quite a lot of memory compared to `glob.sync`. It also looks like `sync` in fact is the faster of the two.

I'll submit a PR.

**Comment by JamieMason** [comment]
Brilliant, thanks @lime that's a great find.

**Comment by JamieMason** [comment]
Making a note of something I've just realised. At the moment I fix _all_ of the missing resolved properties, but resolving the tarball should actually only be needed for packages which 1) need adding to shrinkpack and 2) are not already cached by npm.

**Comment by JamieMason** [comment]
@lime's glob.sync change has been released and the change in https://github.com/JamieMason/shrinkpack/commit/b2cf8b3d6c1ca9bffd8a9a24b36145f9ed8df536 should also help a lot once released.

**Comment by JamieMason** [comment]
let me know if it's any better in the latest version @markerikson?

**Comment by markerikson** [comment]
Ah... yes, sorry, been busy with other tasks.  Overall, it appears to be _much_ better at this point.  Thanks for all your hard work on this!
