### ISSUE TITLE
Shrinkpack crashes when updating dependencies

### ISSUE THREAD

**Issue by objerke** [JamieMason/shrinkpack#34]
#### Expected behaviour

shrinkpack command produces an updated npm-shrinkwrap.json and an updated node_shrinkwrap folder when a new package has been installed and npm shrinkwrap --dev has been executed.
#### Actual behaviour

Shrinkpack gets a type error and crashes.
#### Steps to reproduce
1. Create a new folder 
2. Run `npm init -y`
3. Install shrinkpack globally `npm install shrinkpack --global`
4. Run `npm install ava@0.13.0 --save-dev`
5. Run `npm shrinkwrap --dev`
6. Run `shrinkpack``
   1. npm-shrinkwrap.json is updated with relative file paths
   2. node_shrinkwrap folder is created
7. Run `npm intall ava@0.14.0 --save-dev`
8. Run `npm shrinkwrap --dev`
9. Run `shrinkpack`
#### Software versions used

```
OS         : Windows 10
node.js    : 5.10.1
npm        : 3.3.6
shrinkpack : 0.10.0
```
#### Log output when running shrinkpack

```
! Please raise an issue at https://github.com/JamieMason/shrinkpack/issues

    TypeError: Cannot read property 'shrinkpack' of undefined
        at removeDep (C:\Users\objerke\AppData\Roaming\npm\node_modules\shrinkpack\task\removeFromBundle.js:16:32)
        at Array.map (native)
        at Object.removeFromBundle (C:\Users\objerke\AppData\Roaming\npm\node_modules\shrinkpack\task\removeFromBundle.js:12:27)
        at removeFromBundle (C:\Users\objerke\AppData\Roaming\npm\node_modules\shrinkpack\index.js:48:15)
        at process._tickCallback (internal/process/next_tick.js:103:7)
```
#### Contents of your npm-shrinkwrap.json or package.json

I've created a zip file containing the files in different versions. One for each step.
[shrinkpack-demo.zip](https://github.com/JamieMason/shrinkpack/files/225438/shrinkpack-demo.zip)

**Comment by JamieMason** [comment]
Thanks @objerke, looking now.

**Comment by JamieMason** [comment]
Ah, I've just seen the version is 0.10.0, please try 0.10.2 as I think this issue is the same as #30.

Please reopen if you still have issues. thanks.

**Comment by objerke** [comment]
Thank you, the new version worked!
