### ISSUE TITLE
Add a contributors.md

### ISSUE THREAD

**Issue by 5id** [JamieMason/shrinkpack#49]
It would be great to have a contributors.md file to make getting set up and familiarising with the project easy

Off the top of my head probably the main things would be:
- Code style (semi-standard)
- Format for creating issues, e.g. feat(shrinkpack): description
- How to install / test the package
- What tests should be included

Github has a link to guidelines here, with links to example: https://github.com/blog/1184-contributing-guidelines

Just so it doesn't get lost, as per your comments in #48, it would be good to see if that section of the dependencies.md to not be generated.

**Comment by JamieMason** [comment]
Good idea @5id, thanks.
