### ISSUE TITLE
Add --dev flag option

### ISSUE THREAD

**Issue by aliebuck** [JamieMason/shrinkpack#5]
See shrinkwrap notes: https://docs.npmjs.com/cli/shrinkwrap#other-notes

**Comment by JamieMason** [comment]
Thanks @jacobbuck, this will definitely land.

**Comment by aliebuck** [comment]
Cool :+1:

**Comment by JamieMason** [comment]
0.2.1 ([changelog](https://github.com/JamieMason/shrinkpack/blob/master/CHANGELOG.md)) has the --dev flag set by default, but this will also be made configurable in the future.

**Comment by aliebuck** [comment]
Nice one :smile:
