### ISSUE TITLE
Speed up Dockerised tests

### ISSUE THREAD

**Issue by JamieMason** [JamieMason/shrinkpack#52]
> I'm really new to Docker so excuse me if any of the following is plain wrong, help or contributions welcome.

I think a lot of gains can be made by making better use of the [Dockerfile](https://github.com/JamieMason/shrinkpack/blob/master/Dockerfile), by moving things we wait for during the run phase into the build phase.

**Notes/Ideas**
- Where we currently have `FROM node:4.2.4`, reference a base image which sets up the `shrinkpack` test environment. 
  
  In the `Dockerfile` for that base image;
  - Prime the npm cache by running `npm cache add npm@x.x.x` for every version of `npm` we're interested in.
  - Start some kind of caching proxy (maybe [`sinopia`](https://github.com/rlidwka/sinopia)).
  - Prime the npm cache and populate the caching proxy by running `npm install` against the [`test/package.json`](https://github.com/JamieMason/shrinkpack/blob/master/test/package.json).
- When switching npm versions, `npm rebuild` might be needed.
- Will likely need to change the config cache-min to be something high so npm doesn't try to refetch

See also: https://github.com/JamieMason/shrinkpack/pull/47#issuecomment-228684289 from @5id.

**Comment by 5id** [comment]
I experimented with something similar where I moved the npm install of the control folder into the dockerfile, before realising that it stuffed up supporting different npm versions; so I think that's a much better way to tackle it.

You'll likely need to change the config cache-min to be something high so npm doesn't try to refetch.

Running the caching proxy in the same Dockerfile is possible, though you might find it makes it a bit messy. Potentially you could prime the local cache with an npm install to get a small bump to avoid using the proxy, but the downside of not using something like sinopia is the lack of ability to test private repos like we need for #47

**Comment by JamieMason** [comment]
Updated to include your point on cache-min, cheers! agree re: private repos too.
