### ISSUE TITLE
Please help me install phantomjs2-ext

### ISSUE THREAD

**Issue by lonormaly** [JamieMason/shrinkpack#57]
Hello,

Thanks for this amazing tool! 
For some reason, we fail to install Phantomjs-ext. Any idea on how to achieve that?

Cheers,
Shai

**Comment by JamieMason** [comment]
Hi Shai, I'm away until the weekend but will take a look when I get back. Thanks.

**Comment by JamieMason** [comment]
Hi @lonormaly,
I followed these steps and was able to install, shrinkpack, and reinstall `phantomjs2-ext`.

```
mkdir test
cd test
npm init -y
npm install phantomjs2-ext
npm shrinkwrap --dev
shrinkpack
rm -rf node_modules/
npm install
```

I am using

```
$ node -v
v6.2.2

$ npm -v
3.10.4

$ shrinkpack -V
0.12.5
```

Please could you let me know if this works for you, please reopen if you have any issues.

Thanks.
