### ISSUE TITLE
cache entry in .npmrc is ignored

### ISSUE THREAD

**Issue by skirmess** [JamieMason/shrinkpack#6]
Shrinkpack ignores the cache entry in .npmrc and tries to read the files from ~/.npm

**Comment by JamieMason** [comment]
Thanks @skirmess, I'd not seen the [cache config](https://docs.npmjs.com/misc/config#cache) before. I'll make sure I account for that.

**Comment by JamieMason** [comment]
Landed in 0.3.0. (https://github.com/JamieMason/shrinkpack/blob/master/index.js#L55)
