### ISSUE TITLE
"The system cannot find the path specified." issue when running on Windows 7

### ISSUE THREAD

**Issue by JasonHewison** [JamieMason/shrinkpack#7]
When I installed this on windows I couldn't get it to work (I did manage to after a few work arounds).

When running shrinkpack I get the error;

``` bash
"The system cannot find the path specified."
```

To get it to work I had to do the following;
- Change the shrinkpack.cmd file to run shrinkpack.js by copying and editing the cmd file gulp creates.
- Everywhere that "process.env.PWD" is referenced change it to "process.env.PWD || process.cwd()"
- In tarball.js change 'USERPROFILE' to 'APPDATA'

I also needed to change npm shrinkwrap to npm shrinkwrap --dev because we needed dev dependencies to be shrinked.

I've forked this and tested a change that works on windows, but haven't tested this on any other OS - https://github.com/JasonHewison/shrinkpack

**Comment by JamieMason** [comment]
Really appreciate this, your Pull Request has been merged and released Jason.

**Comment by JamieMason** [comment]
0.2.1 ([changelog](https://github.com/JamieMason/shrinkpack/blob/master/CHANGELOG.md)) released to npm.

I forgot to do this at the time.
