### ISSUE TITLE
shrinkpack 'is not recognized....' on Windows 10

### ISSUE THREAD

**Issue by grant-unwin** [JamieMason/shrinkpack#79]
Installing runs just fine:
`npm install --global shrinkpack`

Then when running `shrinkpack` it returns 
```
'shrinkpack' is not recognized as an internal or external command,
operable program or batch file.
```
Is there a reason this may not work in this way for Windows?

**Comment by JamieMason** [comment]
What output do you get for the following please?

```
npm install --global eslint
eslint --help
```

**Comment by grant-unwin** [comment]
Same result.

```
'eslint' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by JamieMason** [comment]
There seems to be some issue with your npm installation or PATH settings, there should be some answers on google search or stackoverflow.com to get you set up 👍
